### ISSUE TITLE
There should be a way to use the agent with vanilla Node.js requests (not just Express)

### ISSUE THREAD

**Issue by zoltantarcsay** [zoltantarcsay/node-openam-agent#10]

**Comment by sidkshatriya** [comment]
It would be interesting to know how one can go about doing this currently using the shield architecture.

**Comment by zoltantarcsay** [comment]
The agent would need to be refactored somewhat so that it doesn't rely on things set by Express.

**Comment by sidkshatriya** [comment]
Also how would we simply evaluate the "result"/outcome of the shield (rather than the shield itself throw an HTTP response as part of the middleware?).

**Comment by zoltantarcsay** [comment]
This works out of the box:

```javascript
var http = require('http'),
    openamAgent = require('openam-agent'),
    PolicyAgent = openamAgent.PolicyAgent,
    CookieShield = openamAgent.CookieShield;

var agent = new PolicyAgent({
        serverUrl: 'http://openam.example.com:8080/openam',
        appUrl: 'http://app.example.com:3000',
        logLevel: 'silly'
    }),
    shield = new CookieShield({
        getProfiles: true
    });


shield.init(agent);

var server = http.createServer(function (req, res) {
    if (req.url.match(/some\/path$/)) {
        shield.evaluate(req, function (sessionKey, sessionData) {
            // success
            agent.sessionCache.put(sessionKey, sessionData);

            // app logic
            res.writeHead(200);
            res.write('Hello ' + sessionData.username + '!');
            res.end();

        }, function (status, message, details) {
            // failure
            res.writeHead(status || 403);
            res.write(message);
            res.write(details);
            res.end();
        })
    } else {
        res.writeHead(404);
        res.write('Not found');
        res.end();
    }
});

server.listen(3000);
```

However the CookieShield barfs when it tries to check the request host name before it redirects to OpenAM. If you already have a valid session, then it's fine. A small change in CookieShield could make it independent from Express JS.

**Comment by zoltantarcsay** [comment]
I refactored some stuff and released a new major version (3.0) as I had to change the method signature of `Shield#evaluate()`.
I also added an example app to the demo repo: https://github.com/zoltantarcsay/node-openam-agent-demo/blob/master/lib/example1/index.js

**Comment by sidkshatriya** [comment]
@zoltantarcsay Thanks so much for taking the time and effort to write the above example! A small hint would have been fine :-) 

So, essentially  `shield.evaluate()` returns a promise. The `.then()` branch of the promise is a shield allow and the `.catch` branch is a shield deny/some authentication error.

I also saw the example (using the new API) at https://github.com/zoltantarcsay/node-openam-agent-demo/blob/master/lib/example1/index.js though it does not seem to map exactly to the example you posted here (or does it?). For instance, I don't see a failure branch for the `middleware` function. Maybe you include that in the example if you think its useful?

**Comment by zoltantarcsay** [comment]
An Express middleware is not a promise, but a function with 3 arguments: req, res and next (the latter being a success callback). Any errors are supposed to be handled inside the middleware. Also, a policy agent's job is to block unauthorized requests. If it were up to the app developer to handle failures, they could choose to ignore them which would defeat the purpose of a shield.

That said, you can circumvent the middleware and use shield.evaluate() directly, which just returns a promise:

```javascript
var agent = new PolicyAgent(config);
var shield = new CookieShield();

http.createServer(function(req, res) {
    shield.evaluate(req, res, agent)
        .then(function () { 
            // do stuff and return a resource
        })
        .catch(function (err) {
            // handle the error return an error response
        });
});

server.listen(3000);
```
