### ISSUE TITLE
Move Shield plugins to separate repos and node packages

### ISSUE THREAD

**Issue by zoltantarcsay** [zoltantarcsay/node-openam-agent#15]

**Comment by sidkshatriya** [comment]
I was wondering if it might be a better idea to keep things in one repo/node package for now. It keeps the complexity/understandability of the whole agent in check. The separation of the plugin in the code is already quite clear and clean. Of course, this is just my opinion and this is a decision for you to make :-) !

**Comment by zoltantarcsay** [comment]
Good point... I decided to split out the caches because they added a lot of dependencies, however shields don't really depend on anything, so they can stay for now.
