### ISSUE TITLE
How to do CDSSO with 2.2 Agents in openam-agent

### ISSUE THREAD

**Issue by sidkshatriya** [zoltantarcsay/node-openam-agent#17]
Can you tell me how I can configure cross domain SSO using the 2.2 Policy Agents so that this would work with OpenAM? Or do I need to setup some other kind of agents in OpenAM?

(Also its not clear if 2.2 agents are the only agents supported by node-openam-agent)

I have a server abc.example.com which has openAM. I want it to be able to use cookie shield functionalities for xyz.example.com

**Comment by zoltantarcsay** [comment]
I you want CDSSO, you'll need a web agent profile (rather than a 2.2). Then just configure CDSSO in the agent profile as usual.
As for the app code, see the example at https://github.com/zoltantarcsay/node-openam-agent/wiki/PolicyAgent#PolicyAgent+cdsso
